### PR TITLE
Removed unecessary comments

### PR DESCRIPTION
**Pull request by borntohonk**
Pointless lines that only contribute to polarizing things, and cause distractions.

### CODE REVIEW

**Comment by Qyriad** [comment]
This will not be considered. These lines are here for a reason.

**Comment by borntohonk** [comment]
That reason being to bait and provoke bullying.

It's missing perspective.

**Comment by altdadada** [comment]
u gay

**Comment by altdadada** [comment]
trannies are just failed men and should feel shame for shaming the male demographic u born with a hot dog u always a male no matter how much trash u eat

**Pull request closed without merging**
